# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=resumematcher
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/resumematcher
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
